# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window4.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.panelWidget = QtWidgets.QWidget(self.centralwidget)
        self.panelWidget.setMinimumSize(QtCore.QSize(482, 0))
        self.panelWidget.setObjectName("panelWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.panelWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.controlWidget = QtWidgets.QWidget(self.panelWidget)
        self.controlWidget.setObjectName("controlWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.controlWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.clearButton = QtWidgets.QPushButton(self.controlWidget)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout.addWidget(self.clearButton, 2, 4, 1, 1)
        self.pauseButton = QtWidgets.QPushButton(self.controlWidget)
        self.pauseButton.setObjectName("pauseButton")
        self.gridLayout.addWidget(self.pauseButton, 2, 3, 1, 1)
        self.controlsLabel = QtWidgets.QLabel(self.controlWidget)
        self.controlsLabel.setObjectName("controlsLabel")
        self.gridLayout.addWidget(self.controlsLabel, 0, 0, 1, 1)
        self.stepButton = QtWidgets.QPushButton(self.controlWidget)
        self.stepButton.setObjectName("stepButton")
        self.gridLayout.addWidget(self.stepButton, 2, 2, 1, 1)
        self.playButton = QtWidgets.QPushButton(self.controlWidget)
        self.playButton.setObjectName("playButton")
        self.gridLayout.addWidget(self.playButton, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.controlWidget, 1, 1, 1, 1)
        self.optionWidget = QtWidgets.QWidget(self.panelWidget)
        self.optionWidget.setObjectName("optionWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.optionWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stepLabel = QtWidgets.QLabel(self.optionWidget)
        self.stepLabel.setObjectName("stepLabel")
        self.verticalLayout_3.addWidget(self.stepLabel)
        self.optionsLabel = QtWidgets.QLabel(self.optionWidget)
        self.optionsLabel.setObjectName("optionsLabel")
        self.verticalLayout_3.addWidget(self.optionsLabel)
        self.speedSlider = QtWidgets.QSlider(self.optionWidget)
        self.speedSlider.setMaximum(30)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setObjectName("speedSlider")
        self.verticalLayout_3.addWidget(self.speedSlider)
        self.speedLabel = QtWidgets.QLabel(self.optionWidget)
        self.speedLabel.setObjectName("speedLabel")
        self.verticalLayout_3.addWidget(self.speedLabel)
        self.gridLayout_2.addWidget(self.optionWidget, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.panelWidget, 1, 0, 1, 1)
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayoutWidget = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3.addWidget(self.gridWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 621, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/file-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/file-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save.setIcon(icon1)
        self.action_Save.setObjectName("action_Save")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/file-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon2)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Rules = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/help-content.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Rules.setIcon(icon3)
        self.action_Rules.setObjectName("action_Rules")
        self.action_How_to_play = QtWidgets.QAction(MainWindow)
        self.action_How_to_play.setIcon(icon3)
        self.action_How_to_play.setObjectName("action_How_to_play")
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Exit)
        self.menuHelp.addAction(self.action_Rules)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.action_How_to_play)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.controlsLabel.setText(_translate("MainWindow", "Controls"))
        self.stepButton.setText(_translate("MainWindow", "Next Step"))
        self.playButton.setText(_translate("MainWindow", "Play"))
        self.stepLabel.setText(_translate("MainWindow", "Step:"))
        self.optionsLabel.setText(_translate("MainWindow", "Options"))
        self.speedLabel.setText(_translate("MainWindow", "Fps:"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_Open.setToolTip(_translate("MainWindow", "Open existing configuration"))
        self.action_Open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_Save.setText(_translate("MainWindow", "&Save"))
        self.action_Save.setToolTip(_translate("MainWindow", "Save configuration"))
        self.action_Save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_Exit.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.action_Rules.setText(_translate("MainWindow", "Rules"))
        self.action_Rules.setToolTip(_translate("MainWindow", "Rules of the game"))
        self.action_How_to_play.setText(_translate("MainWindow", "How to play"))

